export const tableHead = {
    date: "Date",
    title: "Title",
    speaker: "Speaker",
    speaker_org: "Speaker Organisation",
    total_students: "Total Students",
    total_student: "Total Students",
    batch: "Batch",
    mode: "Mode",
    department: "Department",
    sem: 'Semester',
    status: 'Status',
    student_members: 'Student Members',
    faculty_cordinators: 'Faculty Cordinators',
    start_date: 'Start Date',
    end_date: 'End Date',
    total_events: 'Total Events',
    total_participants: 'Total Participants',
    special_event: 'Special Event',
    aamod_cup:'Aamod Cup',
    president:'President',
    secretary:'Secretary',
    vice_president:'Vice President',
    trust_secretary:'Trust Secretary',
    joint_secretary:'Joint Secretary',
    total_scholarship:'Total Scholarship',
    students_awarded:"Students Awarded",
    highest_scholarship:"Highest Scholarship",
    chief_guest:"Chief Guest",
    chief_guest_designation:"Chief Guest Designation",
    presiding_officer:"Presiding Officer",
    presiding_officer_designation:"Presiding Officer Designation",
    guest_of_honour:"Guest of Honour",
    organized_by:"Organized By",
    total_alumini_attended:"Total Alumini Attended",
    venue:"Venue",
    faculty_incharge:"Faculty Incharge",
    total_teams:'Total Teams',
    guest:"Guest",
    judges:'Judegs',
    event:"Event",
    year:"Year",
    collaboration_org:"Collaboration Org",
    exam_type:'Exam Type',
    qualified_students:'Qualified Students'

}

export const table1stRow = {
    'guest_lecture': ['title', 'date', 'speaker', 'speaker_org', 'total_student', 'sem', 'batch', 'mode', 'department'],
    'patent': ['title', 'date', 'sem', 'status', 'student_members', 'faculty_cordinators'],
    'zest': ['title', 'start_date', 'end_date', 'sem', 'total_events', 'total_participants', 'special_event'],
    'aamod': ['title', 'start_date', 'end_date', 'sem', 'total_events', 'total_participants', 'aamod_cup'],
    'techvyom': ['title', 'date', 'sem', 'total_events', 'total_participants'],
    'scholarship': [ 'date', 'sem', 'total_scholarship', 'students_awarded','highest_scholarship'],
    'oath_ceremony':['date','president','secretary','trust_secretary','vice_president','joint_secretary'],
    'convocation':['date','sem','chief_guest','chief_guest_designation','presiding_officer','presiding_officer_designation','guest_of_honour'],
    'workshop':['title','start_date','end_date','speaker','sem','organized_by','total_students','department'],
    'alumini_meet':['date','sem','venue','total_alumini_attended','organized_by'],
    'industrial_visit':['organization','organized_by','faculty_incharge','start_date','end_date','sem','total_students','department'],
    'hackathon':['title','start_date','end_date','sem','organized_by','total_participants','total_teams','guest','judges','faculty_incharge'],
    'day_celebration':['event','date','sem','year'],
    'bootcamp':['title','start_date','end_date','organized_by','speaker','speaker_org','collaboration_org','total_students','mode','department'],
    'conference':['title','start_date','end_date','speaker','speaker_org','sem','organized_by','total_students','batch','mode','department'],
    'seminar':['title','start_date','end_date','speaker','speaker_org','sem','organized_by','total_students','batch','mode','department'],
    'important_exam':['exam_type','date','qualified_students','total_participants']
}
export const blogSide = {
    'guest_lecture': ['sem', 'speaker', 'speaker_org', 'total_student', 'batch', 'mode', 'department'],
    'patent': ['sem', 'status', 'student_members', 'faculty_cordinators'],
    'zest': ['title', 'sem', 'total_events', 'total_participants', 'special_event'],
    'aamod': ['sem', 'total_events', 'total_participants', 'aamod_cup'],
    'techvyom': ['sem', 'total_events', 'total_participants'],
    'scholarship': [ 'sem', 'total_scholarship', 'students_awarded','highest_scholarship'],
    'oath_ceremony':['president','secretary','trust_secretary','vice_president','joint_secretary'],
    'convocation':['sem','chief_guest','chief_guest_designation','presiding_officer','presiding_officer_designation','guest_of_honour'],
    'workshop':['speaker','speaker_org','sem','organized_by','total_students','batch','mode','department'],
    'alumini_meet':['sem','venue','total_alumini_attended','organized_by'],
    'industrial_visit':['sem','organization','organized_by','faculty_incharge','total_students','department'],
    'hackathon':['organized_by','total_participants','total_teams','sem','guest','judges','faculty_incharge'],
    'day_celebration':['event','date','sem','year'],
    'bootcamp':['sem','organized_by','speaker','speaker_org','collaboration_org','total_students','batch','mode','department'],
    'conference':['speaker','speaker_org','sem','organized_by','total_students','batch','mode','department'],
    'seminar':['speaker','speaker_org','venue','sem','organized_by','total_students','batch','mode','department'],
    'important_exam':['exam_type','qualified_students','total_participants']
    
}